version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:latest
    container_name: keycloak_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build: .
    container_name: keycloak_custom
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
